### PR TITLE
Tpar editor

### PR DESCRIPTION
**Pull request by rerpha**

### CODE REVIEW

**Review by Chsudeepta — COMMENTED** [review]
Are we expected to also write some system tests for these changes?

**Comment by rerpha** [comment]
> Are we expected to also write some system tests for these changes?

we could do, but i think the ones in ioc test framework should be enough to cover what's needed? I didn't write one for writing a file, but could probably add one

**Comment by rerpha** [comment]
jsut a note - we can't do anything about the switching window behaviour as it's a wider cs studio issue rather than specific to this. I have fixed the file saving if it hasnt changed, and have also fixed the line ending issue where it was putting extra line endings.

**Review by Chsudeepta — APPROVED** [review]
working as expected

**Pull request merged**
